apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-log-pipeline
data:
  apache.conf: |
    input {
            beats {
            port => "5044"
        }
    }
    filter {
        grok {
            match => { "message" => "%{COMBINEDAPACHELOG}"}
        }
    }
    output {
        elasticsearch {
            hosts => ["http://elasticsearch-loadbalancer:9200"]
            index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
        }
        stdout { 
            codec => rubydebug 
          }
    }
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch-loadbalancer:9200" ]
  pipelines.yml: |
    # This file is where you define your pipelines. You can define multiple.
    # For more information on multiple pipelines, see the documentation:
    #   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

    - pipeline.id: main
      path.config: "/usr/share/logstash/pipeline"

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: apache-log-pipeline
spec:
  template:
    metadata:
      labels:
        app: apache-log-pipeline
    spec:
      hostname: apache-log-pipeline
      containers:
      - name: apache-log-pipeline
        ports:
          - containerPort: 5044
            name: filebeat
          - containerPort: 9600
            name: logstash
        image: docker.elastic.co/logstash/logstash:7.0.0
        volumeMounts:
        - name: apache-log-pipeline-config
          mountPath: /usr/share/logstash/pipeline/
        - name: logstash-config
          mountPath: /usr/share/logstash/config/
        command:
        - logstash
      volumes:
      - name: apache-log-pipeline-config
        configMap:
          name: apache-log-pipeline
          items:
          - key: apache.conf
            path: apache.conf
      - name: logstash-config
        configMap:
          name: logstash-config
          items:
          - key: logstash.yml
            path: logstash.yml
          items:
          - key: pipelines.yml
            path: pipelines.yml
---

kind: Service
apiVersion: v1
metadata:
  name: apache-log-pipeline
spec:
  type: NodePort
  selector:
    app: apache-log-pipeline
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
    nodePort: 30102
    name: filebeat
  - protocol: TCP
    port: 9600
    targetPort: 9600
    name: logstash

